/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (c) 2025 MediaTek Inc. All Rights Reserved.
 *
 */

#ifndef _NPU_MCAST_CMD_H_
#define _NPU_MCAST_CMD_H_

/* net command */
enum npu_mcast_cmd {
	NPU_MCAST_NET_CMD_NULL,
	NPU_MCAST_NET_CMD_SET,
	NPU_MCAST_NET_CMD_SET_MAC_SADDR,
	NPU_MCAST_NET_CMD_GET,
	NPU_MCAST_NET_CMD_GET_MAC_SADDR,
	NPU_MCAST_NET_CMD_PARAMS,
	NPU_MCAST_NET_CMD_STATISTIC,

	__NPU_MCAST_NET_CMD_MAX,
};

enum npu_mcast_set_cmd {
	NPU_MCAST_NET_CMD_SET_NULL,
	NPU_MCAST_NET_CMD_SET_EN,
	NPU_MCAST_NET_CMD_SET_QOS_EN,
	NPU_MCAST_NET_CMD_SET_TID_EN,
	NPU_MCAST_NET_CMD_SET_STATISTIC_EN,

	__NPU_MCAST_NET_CMD_SET_MAX,
};

enum npu_mcast_get_cmd {
	NPU_MCAST_NET_CMD_GET_NULL,
	NPU_MCAST_NET_CMD_GET_EN,
	NPU_MCAST_NET_CMD_GET_QOS_EN,
	NPU_MCAST_NET_CMD_GET_TID_EN,
	NPU_MCAST_NET_CMD_GET_STATISTIC_EN,

	__NPU_MCAST_NET_CMD_GET_MAX,
};

enum npu_mcast_params_cmd {
	NPU_MCAST_NET_CMD_GRP_PARAMS_UPDATE,
	NPU_MCAST_NET_CMD_GRP_PARAMS_BASE_ADDR_GET,
	NPU_MCAST_NET_CMD_BSS_PARAMS_UPDATE,
	NPU_MCAST_NET_CMD_BSS_PARAMS_BASE_ADDR_GET,

	__NPU_MCAST_NET_CMD_PARAMS_MAX,
};

enum npu_mcast_statistic_cmd {
	NPU_MCAST_NET_CMD_STATISTIC_BASE_ADDR_GET,
	NPU_MCAST_NET_CMD_STATISTIC_CLEAR,
	NPU_MCAST_NET_CMD_STATISTIC_CLIENT_CLEAR,
};
#endif /* _NPU_MCAST_CMD_H_ */
