#
# Copyright (C) 2023 Mediatek Ltd.
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

OPTEE_CLIENT_MAKE_FLAGS := CFG_TEE_FS_PARENT_PATH=$(CONFIG_OPTEE_FS_PARENT_PATH) \
			   CFG_TA_TEST_PATH=$(CONFIG_OPTEE_TA_TEST_PATH) \
			   RPMB_EMU=$(CONFIG_OPTEE_RPMB_EMU)

ifeq ($(CONFIG_OPTEE_CLIENT_LOG_LEVEL_NONE),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_CLIENT_LOG_LEVEL=0
else ifeq ($(CONFIG_OPTEE_CLIENT_LOG_LEVEL_ERROR),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_CLIENT_LOG_LEVEL=1
else ifeq ($(CONFIG_OPTEE_CLIENT_LOG_LEVEL_INFO),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_CLIENT_LOG_LEVEL=2
else ifeq ($(CONFIG_OPTEE_CLIENT_LOG_LEVEL_DEBUG),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_CLIENT_LOG_LEVEL=3
else ifeq ($(CONFIG_OPTEE_CLIENT_LOG_LEVEL_FLOW),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_CLIENT_LOG_LEVEL=4
endif

ifeq ($(CONFIG_OPTEE_SUPP_LOG_LEVEL_NONE),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_SUPP_LOG_LEVEL=0
else ifeq ($(CONFIG_OPTEE_SUPP_LOG_LEVEL_ERROR),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_SUPP_LOG_LEVEL=1
else ifeq ($(CONFIG_OPTEE_SUPP_LOG_LEVEL_INFO),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_SUPP_LOG_LEVEL=2
else ifeq ($(CONFIG_OPTEE_SUPP_LOG_LEVEL_DEBUG),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_SUPP_LOG_LEVEL=3
else ifeq ($(CONFIG_OPTEE_SUPP_LOG_LEVEL_FLOW),y)
OPTEE_CLIENT_MAKE_FLAGS += CFG_TEE_SUPP_LOG_LEVEL=4
endif
