#
# Copyright (C) 2026 MediaTek Inc. All rights reserved.
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

PKG_CONFIG_DEPENDS += \
	CONFIG_OPTEE_DEBUG_INFO \
	CONFIG_OPTEE_CORE_DEBUG \
	CONFIG_OPTEE_CORE_MALLOC_DEBUG \
	CONFIG_OPTEE_CORE_SANITIZE_UNDEFINED \
	CONFIG_OPTEE_CORE_SANITIZE_KADDRESS \
	CONFIG_OPTEE_CORE_DEBUG_CHECK_STACKS \
	CONFIG_OPTEE_CORE_TA_TRACE \
	CONFIG_OPTEE_TA_STATS \
	CONFIG_OPTEE_TA_MALLOC_DEBUG \
	CONFIG_OPTEE_CORE_DYN_SHM \
	CONFIG_OPTEE_REE_FS \
	CONFIG_OPTEE_RPMB_FS \
	CONFIG_OPTEE_RPMB_FS_DEBUG_DATA \
	CONFIG_OPTEE_RPMB_WRITE_KEY \
	CONFIG_OPTEE_RPMB_TESTKEY \
	CONFIG_OPTEE_REE_FS_ALLOW_RESET \
	CONFIG_OPTEE_ENABLE_EMBEDDED_TESTS \
	CONFIG_BL32_TZRAM_BASE \
	CONFIG_BL32_TZRAM_SIZE \
	CONFIG_BL32_LOAD_OFFSET \
	CONFIG_OPTEE_CORE_LOG_LEVEL_NONE \
	CONFIG_OPTEE_CORE_LOG_LEVEL_ERROR \
	CONFIG_OPTEE_CORE_LOG_LEVEL_INFO \
	CONFIG_OPTEE_CORE_LOG_LEVEL_DEBUG \
	CONFIG_OPTEE_CORE_LOG_LEVEL_FLOW \
	CONFIG_OPTEE_TA_LOG_LEVEL_NONE \
	CONFIG_OPTEE_TA_LOG_LEVEL_ERROR \
	CONFIG_OPTEE_TA_LOG_LEVEL_INFO \
	CONFIG_OPTEE_TA_LOG_LEVEL_DEBUG \
	CONFIG_OPTEE_TA_LOG_LEVEL_FLOW \
	CONFIG_OPTEE_DRAM_BASE \
	CONFIG_OPTEE_DRAM_SIZE \
	CONFIG_OPTEE_MTK_TEST \
	CONFIG_OPTEE_MTK_TEST_FIPS \
	CONFIG_OPTEE_FW_ENC_EARLY_TA

OPTEE_OS_CONFIGS := \
	CFG_DEBUG_INFO=$(CONFIG_OPTEE_DEBUG_INFO) \
	CFG_TEE_CORE_DEBUG=$(CONFIG_OPTEE_CORE_DEBUG) \
	CFG_TEE_CORE_MALLOC_DEBUG=$(CONFIG_OPTEE_CORE_MALLOC_DEBUG) \
	CFG_CORE_SANITIZE_UNDEFINED=$(CONFIG_OPTEE_CORE_SANITIZE_UNDEFINED) \
	CFG_CORE_SANITIZE_KADDRESS=$(CONFIG_OPTEE_CORE_SANITIZE_KADDRESS) \
	CFG_CORE_DEBUG_CHECK_STACKS=$(CONFIG_OPTEE_CORE_DEBUG_CHECK_STACKS) \
	CFG_TEE_CORE_TA_TRACE=$(CONFIG_OPTEE_CORE_TA_TRACE) \
	CFG_TA_STATS=$(CONFIG_OPTEE_TA_STATS) \
	CFG_TEE_TA_MALLOC_DEBUG=$(CONFIG_OPTEE_TA_MALLOC_DEBUG) \
	CFG_CORE_DYN_SHM=$(CONFIG_OPTEE_CORE_DYN_SHM) \
	CFG_REE_FS=$(CONFIG_OPTEE_REE_FS) \
	CFG_RPMB_FS=$(CONFIG_OPTEE_RPMB_FS) \
	CFG_RPMB_FS_DEBUG_DATA=$(CONFIG_OPTEE_RPMB_FS_DEBUG_DATA) \
	CFG_RPMB_WRITE_KEY=$(CONFIG_OPTEE_RPMB_WRITE_KEY) \
	CFG_RPMB_TESTKEY=$(CONFIG_OPTEE_RPMB_TESTKEY) \
	CFG_REE_FS_ALLOW_RESET=$(CONFIG_OPTEE_REE_FS_ALLOW_RESET) \
	CFG_ENABLE_EMBEDDED_TESTS=$(CONFIG_OPTEE_ENABLE_EMBEDDED_TESTS) \
	CFG_BL32_TZRAM_BASE=$(CONFIG_BL32_TZRAM_BASE) \
	CFG_BL32_TZRAM_SIZE=$(CONFIG_BL32_TZRAM_SIZE) \
	CFG_BL32_LOAD_OFFSET=$(CONFIG_BL32_LOAD_OFFSET)

ifeq ($(CONFIG_OPTEE_CORE_LOG_LEVEL_NONE),y)
OPTEE_OS_CONFIGS += CFG_TEE_CORE_LOG_LEVEL=0
else ifeq ($(CONFIG_OPTEE_CORE_LOG_LEVEL_ERROR),y)
OPTEE_OS_CONFIGS += CFG_TEE_CORE_LOG_LEVEL=1
else ifeq ($(CONFIG_OPTEE_CORE_LOG_LEVEL_INFO),y)
OPTEE_OS_CONFIGS += CFG_TEE_CORE_LOG_LEVEL=2
else ifeq ($(CONFIG_OPTEE_CORE_LOG_LEVEL_DEBUG),y)
OPTEE_OS_CONFIGS += CFG_TEE_CORE_LOG_LEVEL=3
else ifeq ($(CONFIG_OPTEE_CORE_LOG_LEVEL_FLOW),y)
OPTEE_OS_CONFIGS += CFG_TEE_CORE_LOG_LEVEL=4
endif

ifeq ($(CONFIG_OPTEE_TA_LOG_LEVEL_NONE),y)
OPTEE_OS_CONFIGS += CFG_TEE_TA_LOG_LEVEL=0
else ifeq ($(CONFIG_OPTEE_TA_LOG_LEVEL_ERROR),y)
OPTEE_OS_CONFIGS += CFG_TEE_TA_LOG_LEVEL=1
else ifeq ($(CONFIG_OPTEE_TA_LOG_LEVEL_INFO),y)
OPTEE_OS_CONFIGS += CFG_TEE_TA_LOG_LEVEL=2
else ifeq ($(CONFIG_OPTEE_TA_LOG_LEVEL_DEBUG),y)
OPTEE_OS_CONFIGS += CFG_TEE_TA_LOG_LEVEL=3
else ifeq ($(CONFIG_OPTEE_TA_LOG_LEVEL_FLOW),y)
OPTEE_OS_CONFIGS += CFG_TEE_TA_LOG_LEVEL=4
endif

ifeq ($(CONFIG_OPTEE_CORE_DYN_SHM),y)
ifneq ($(CONFIG_OPTEE_DRAM_BASE),)
OPTEE_OS_CONFIGS += CFG_DRAM_BASE=$(CONFIG_OPTEE_DRAM_BASE)
endif
ifneq ($(CONFIG_OPTEE_DRAM_SIZE),)
OPTEE_OS_CONFIGS += CFG_DRAM_SIZE=$(CONFIG_OPTEE_DRAM_SIZE)
endif
endif

# MTK related configs
OPTEE_OS_CONFIGS += \
	CFG_MTK_TEST=$(CONFIG_OPTEE_MTK_TEST) \
	CFG_MTK_TEST_FIPS=$(CONFIG_OPTEE_MTK_TEST_FIPS) \
	CFG_FW_ENC_EARLY_TA=$(CONFIG_OPTEE_FW_ENC_EARLY_TA)
