#!/bin/sh /etc/rc.common
# Copyright (C) 2024 All Rights Reserved.
# Author: Weijie Gao <weijie.gao@mediatek.com>

START=99
boot() {
	local enabled=$(cat /sys/module/boot_param/parameters/reset_boot_count 2>/dev/null)

	if [ x"${enabled}" = xY ]; then
		echo 1 > /proc/reset_boot_count
	fi
}
