#!/usr/bin/env python3

import argparse
import pprint
import requests
import subprocess

class WeatherData:
    def __init__(self, key, lat, lon):
        url=f'https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={key}'
        response = requests.get(url)
        data = response.json()

        self.pressure_sealevel = float(data['current']['pressure'])
        self.temp_sealevel = float(data['current']['temp']) - 273.15

def sysfs_pressure_get():
    file_path = '/sys/bus/iio/devices/iio:device0/in_pressure_input'

    try:
        process = subprocess.Popen(['cat', file_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, error = process.communicate()

        if process.returncode != 0:
            print(f"Error reading the file {file_path}: {error.decode().strip()}")
            return None

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

    pressure = float(output.decode().strip()) * 10

    return pressure

def sysfs_temp_get():
    file_path = '/sys/bus/iio/devices/iio:device0/in_temp_input'

    try:
        process = subprocess.Popen(['cat', file_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, error = process.communicate()

        if process.returncode != 0:
            print(f"Error reading the file {file_path}: {error.decode().strip()}")
            return None

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

    temp = float(output.decode().strip()) / 1000

    return temp

def altitude_calculate(pressure_sealevel, pressure_target, temp_sealevel):
    '''ISA barometric formula'''

    l  = 0.0065                 # lapse rate of dry air
    r  = 287.0                  # air constant in 'J/kg*K' not 'J/mol*K'
    g  = 9.8                    # gravitational acceleration
    t  = temp_sealevel + 273.15 # sealevel temperature in K (kelvin) not degree celsius
    p0 = pressure_sealevel      # sealevel pressure (hPa)
    p  = pressure_target        # pressure at target area (hPa)

    val = ((((p0 / p)**((r * l) / g)) - 1) * t) / l

    return val

def altitude_write_to_file(filename, altitude):
    with open(filename, 'w') as f:
        f.write(str(altitude))

def main():
    parser = argparse.ArgumentParser(description='altitude-tool is a tool to get the altitude of a coordinate')
    parser.add_argument('-k', '--key', type=str, required=True, help='API key to access openweather API')
    parser.add_argument('-x', '--lon', type=float, required=True, help='Longitude')
    parser.add_argument('-y', '--lat', type=float, required=True, help='Latitude')
    parser.add_argument('-w', '--write', type=str, required=False, help='Write to path')

    args = parser.parse_args()

    key = args.key
    lat = args.lat
    lon = args.lon
    path = args.write

    weather_data = WeatherData(key, lat, lon)

    pressure_sealevel = weather_data.pressure_sealevel
    temp_sealevel = weather_data.temp_sealevel
    pressure_target = sysfs_pressure_get()
    altitude = altitude_calculate(pressure_sealevel, pressure_target, temp_sealevel)

    print(f"pressure_sealevel(hPa): {pressure_sealevel}")
    print(f"pressure_target(hPa):   {pressure_target}")
    print(f"temp_sealevel(c):       {temp_sealevel}")
    print(f"altitude(m):            {altitude}")

    if path != None:
        altitude_write_to_file(path, altitude)

if __name__ == "__main__":
    main()
