/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (c) 2025 MediaTek Inc. All Rights Reserved.
 *
 * Author: Ren-Ting Wang <ren-ting.wang@mediatek.com>
 */

#ifndef _NPU_L4S_H_
#define _NPU_L4S_H_

enum npu_l4s_net_cmd {
	NPU_L4S_NET_CMD_NULL,
	NPU_L4S_NET_CMD_SET,
	NPU_L4S_NET_CMD_GET,

	__NPU_L4S_NET_CMD_MAX,
};

enum npu_l4s_net_cmd_set {
	NPU_L4S_NET_CMD_SET_NULL = 0,
	NPU_L4S_NET_CMD_SET_EN,
	NPU_L4S_NET_CMD_SET_THRESHOLD,
	NPU_L4S_NET_CMD_SET_INTERVAL,
	NPU_L4S_NET_CMD_SET_ALPHA,
	NPU_L4S_NET_CMD_SET_DL_DEFAULT_QID = 5,
	NPU_L4S_NET_CMD_SET_DL_CONGESTED_QID,
	NPU_L4S_NET_CMD_SET_UL_DEFAULT_QID,
	NPU_L4S_NET_CMD_SET_UL_CONGESTED_QID,

	__NPU_L4S_NET_CMD_SET_MAX,
};

enum npu_l4s_net_cmd_get {
	NPU_L4S_NET_CMD_GET_NULL = 0,
	NPU_L4S_NET_CMD_GET_EN,
	NPU_L4S_NET_CMD_GET_THRESHOLD,
	NPU_L4S_NET_CMD_GET_INTERVAL,
	NPU_L4S_NET_CMD_GET_ALPHA,
	NPU_L4S_NET_CMD_GET_DL_DEFAULT_QID = 5,
	NPU_L4S_NET_CMD_GET_DL_CONGESTED_QID,
	NPU_L4S_NET_CMD_GET_UL_DEFAULT_QID,
	NPU_L4S_NET_CMD_GET_UL_CONGESTED_QID,

	__NPU_L4S_NET_CMD_GET_MAX,
};
#endif /* _NPU_L4S_H_ */
